<link rel="stylesheet" type="text/css" href="tpl/css/strappy.css">
<link rel="stylesheet" type="text/css" href="tpl/css/validation.css">
<script src="tpl/js/jquery.min.js"></script>
<script src='tpl/js/bsmin.js'></script>
<script src="tpl/js/jquery.validate.js"></script>
<script src="tpl/js/additional-methods.js"></script>
<script type="text/javascript">
$(document).ready(function(){
  $("#register_form").validate();
});
</script>
